config/routes.rb
Rails.application.routes.draw do
  resources :orders

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @client_token = Braintree::ClientToken.generate
  end
  def create
    nonce = params[:payment_method_nonce]
    render action: :new unless nonce
    result = Braintree::Transaction.sale(
      amount: "10.00",
      payment_method_nonce: nonce
    )

    flash[:notice] = "Sale successful." if result.success?
    flash[:alert] = "something missing. #{result.transaction.processor_response_text}" unless result.success?
    redirect_to action: :new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VzeroSdkTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p><%= notice %></p>
<% end %>
<% if alert %>
  <p><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/orders/new.html.erb
<h1>Welcome to braintree demo</h1>
<%= render 'payments/form' %>

app/views/payments/_form.html.erb
<%= form_tag orders_path, method: 'post' do %>
    <div id="dropin"></div>
      <input type="submit" value="Pay $10">
    <% end %>
    <%= @params %>

    <script type="text/javascript">
function setupBT() {
  braintree.setup("<%=@client_token%>", 'dropin', {
            container: 'dropin'
                
            });
    
}
  if (window.addEventListener)
      window.addEventListener("load", setupBT, false);
        else if (window.attachEvent)
      window.attachEvent("onload", setupBT);
        else window.onload = setupBT;
          </script>
          </script>